name: Build and Deploy

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install and Build   
        run: |
          yarn install
          yarn run build
      - name: Deploy  
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        if: github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: docs/.vuepress/dist
